spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  host: http://localhost:8080