spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql: trace
